[[entries]]
name = "minecraft:protection"
max_lvl = 4

[[entries]]
name = "minecraft:fire_protection"
max_lvl = 4

[[entries]]
name = "minecraft:feather_falling"
max_lvl = 4

[[entries]]
name = "minecraft:blast_protection"
max_lvl = 4

[[entries]]
name = "minecraft:projectile_protection"
max_lvl = 4

[[entries]]
name = "minecraft:respiration"
max_lvl = 3

[[entries]]
name = "minecraft:aqua_affinity"
max_lvl = 1

[[entries]]
name = "minecraft:thorns"
max_lvl = 3

[[entries]]
name = "minecraft:depth_strider"
max_lvl = 3

[[entries]]
name = "minecraft:frost_walker"
max_lvl = 2

[[entries]]
name = "minecraft:binding_curse"
max_lvl = 1

[[entries]]
name = "minecraft:soul_speed"
max_lvl = 3

[[entries]]
name = "minecraft:sharpness"
max_lvl = 5

[[entries]]
name = "minecraft:smite"
max_lvl = 5

[[entries]]
name = "minecraft:bane_of_arthropods"
max_lvl = 5

[[entries]]
name = "minecraft:knockback"
max_lvl = 2

[[entries]]
name = "minecraft:fire_aspect"
max_lvl = 2

[[entries]]
name = "minecraft:looting"
max_lvl = 3

[[entries]]
name = "minecraft:sweeping"
max_lvl = 3

[[entries]]
name = "minecraft:efficiency"
max_lvl = 5

[[entries]]
name = "minecraft:silk_touch"
max_lvl = 1

[[entries]]
name = "minecraft:unbreaking"
max_lvl = 3

[[entries]]
name = "minecraft:fortune"
max_lvl = 3

[[entries]]
name = "minecraft:power"
max_lvl = 5

[[entries]]
name = "minecraft:punch"
max_lvl = 2

[[entries]]
name = "minecraft:flame"
max_lvl = 1

[[entries]]
name = "minecraft:infinity"
max_lvl = 1

[[entries]]
name = "minecraft:luck_of_the_sea"
max_lvl = 3

[[entries]]
name = "minecraft:lure"
max_lvl = 3

[[entries]]
name = "minecraft:loyalty"
max_lvl = 3

[[entries]]
name = "minecraft:impaling"
max_lvl = 5

[[entries]]
name = "minecraft:riptide"
max_lvl = 3

[[entries]]
name = "minecraft:channeling"
max_lvl = 1

[[entries]]
name = "minecraft:multishot"
max_lvl = 1

[[entries]]
name = "minecraft:quick_charge"
max_lvl = 3

[[entries]]
name = "minecraft:piercing"
max_lvl = 4

[[entries]]
name = "minecraft:mending"
max_lvl = 1

[[entries]]
name = "minecraft:vanishing_curse"
max_lvl = 1

[[entries]]
name = "apotheosis:miners_fervor"
max_lvl = 5

[[entries]]
name = "apotheosis:stable_footing"
max_lvl = 1

[[entries]]
name = "apotheosis:scavenger"
max_lvl = 3

[[entries]]
name = "apotheosis:life_mending"
max_lvl = 3

[[entries]]
name = "apotheosis:icy_thorns"
max_lvl = 3

[[entries]]
name = "apotheosis:tempting"
max_lvl = 1

[[entries]]
name = "apotheosis:shield_bash"
max_lvl = 4

[[entries]]
name = "apotheosis:reflective"
max_lvl = 5

[[entries]]
name = "apotheosis:berserkers_fury"
max_lvl = 3

[[entries]]
name = "apotheosis:knowledge"
max_lvl = 3

[[entries]]
name = "apotheosis:splitting"
max_lvl = 1

[[entries]]
name = "apotheosis:natures_blessing"
max_lvl = 3

[[entries]]
name = "apotheosis:rebounding"
max_lvl = 3

[[entries]]
name = "apotheosis:bane_of_illagers"
max_lvl = 5

[[entries]]
name = "apotheosis:obliteration"
max_lvl = 1

[[entries]]
name = "apotheosis:crescendo"
max_lvl = 5

[[entries]]
name = "apotheosis:infusion"
max_lvl = 1

[[entries]]
name = "apotheosis:endless_quiver"
max_lvl = 1

[[entries]]
name = "apotheosis:chromatic"
max_lvl = 1

[[entries]]
name = "apotheosis:exploitation"
max_lvl = 1

[[entries]]
name = "apotheosis:growth_serum"
max_lvl = 1

[[entries]]
name = "apotheosis:earths_boon"
max_lvl = 3

[[entries]]
name = "apotheosis:chainsaw"
max_lvl = 1

[[entries]]
name = "apotheosis:spearfishing"
max_lvl = 5

[[entries]]
name = "apotheosis:capturing"
max_lvl = 5

[[entries]]
name = "tombstone:shadow_step"
max_lvl = 10

[[entries]]
name = "tombstone:soulbound"
max_lvl = 1

[[entries]]
name = "tombstone:magic_siphon"
max_lvl = 10

[[entries]]
name = "tombstone:plague_bringer"
max_lvl = 10

[[entries]]
name = "tombstone:curse_of_bones"
max_lvl = 10

[[entries]]
name = "tombstone:blessing"
max_lvl = 10

[[entries]]
name = "tombstone:frostbite"
max_lvl = 10

[[entries]]
name = "naturesaura:aura_mending"
max_lvl = 1

[[entries]]
name = "miniutilities:shotgun"
max_lvl = 4

[[entries]]
name = "miniutilities:molten_head"
max_lvl = 1

[[entries]]
name = "miniutilities:experience_harvester"
max_lvl = 5

[[entries]]
name = "mythicbotany:hammer_mobility"
max_lvl = 5
